[phases.setup]
nixpkgs = ['php','nodejs','composer']

[phases.install]
cmds = [
    "cd src && composer install --no-dev --optimize-autoloader && npm ci"
]

[phases.build]
cmds = [
    "cd src && npm run build"
]

[phases.start]

cmd = "php src/artisan serve --host=0.0.0.0 --port=8080"